const designSystem = require('./design-system/tokens.json');
const { color, typography } = designSystem;

const semanticTypography = Object.fromEntries(Object.entries(typography).map(([role, token]) => [
  role,
  [`${token.fontSize}px`, {
    lineHeight: `${token.lineHeight}px`, letterSpacing: `${token.letterSpacing}px`,
    fontWeight: token.fontWeight, fontFamily: token.fontFamily,
  }],
]));

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        neutral: { 200: color.border.default },
        lime: { 100: color.native.accentMuted, 700: color.native.accentText },
        background: color.surface.app,
        foreground: color.text.primary,
        subtle: color.surface.subtle,
        muted: color.surface.muted,
        'muted-foreground': color.text.secondary,
        card: color.surface.elevated,
        'card-foreground': color.text.primary,
        popover: color.surface.elevated,
        'popover-foreground': color.text.primary,
        overlay: color.overlay.scrim,
        primary: color.action.primary,
        'primary-hover': color.action.primaryHover,
        'primary-foreground': color.action.primaryText,
        secondary: color.action.secondary,
        'secondary-foreground': color.action.secondaryText,
        accent: color.surface.subtle,
        'accent-foreground': color.text.primary,
        destructive: color.action.destructive,
        'destructive-foreground': color.action.destructiveText,
        border: color.border.default,
        'border-subtle': color.overlay.separator,
        'border-strong': color.border.strong,
        'border-light': color.border.default,
        input: color.border.default,
        ring: color.border.focus,
        disabled: color.action.disabled,
        'disabled-foreground': color.text.disabled,
        'inverted-foreground': color.text.inverted,
        'text-tertiary': color.text.tertiary,
        danger: color.status.danger,
        'danger-subtle': color.status.dangerSurface,
        'danger-border': designSystem.primitives.color.red300,
        'danger-text': designSystem.primitives.color.red700,
        success: color.status.success,
        'success-subtle': color.status.successSurface,
        'success-text': designSystem.primitives.color.green600,
        warning: color.status.warning,
        'warning-subtle': color.status.warningSurface,
        'warning-text': color.status.warningText,
        info: color.status.info,
        'info-subtle': color.status.infoSurface,
        'info-text': color.status.infoText,
        'orange-subtle': color.status.warningSurface,
        'orange-text': color.native.orangeText,
        'accent-bg-light': color.native.accentSurface,
        'accent-fg-light': color.native.accentTextStrong,
        'accent-subtle': color.native.accentSurface,
        'accent-border': color.native.accentBorder,
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        'sans-medium': ['Inter_500Medium'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_700Bold'],
      },
      fontSize: semanticTypography,
      borderRadius: {
        '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px', '6': '24px',
        full: '9999px', sm: '8px', md: '12px', lg: '16px', xl: '24px', '2xl': '24px', '3xl': '24px',
      },
    },
  },
  plugins: [],
};
