#!/usr/bin/env bash

set -euo pipefail

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
apple_root="$(cd "${script_directory}/.." && pwd)"
repository_root="${TAISA_REPOSITORY_ROOT:-$(cd "${apple_root}/.." && pwd)}"
output_path="${1:-${apple_root}/Generated/BuildMetadata.generated.swift}"

git_commit="$(git -C "${repository_root}" rev-parse HEAD)"
git_branch="$(git -C "${repository_root}" symbolic-ref --quiet --short HEAD || true)"
if [[ -n "$(git -C "${repository_root}" status --porcelain --untracked-files=all)" ]]; then
  is_dirty='true'
else
  is_dirty='false'
fi
contract_revision='transcription-fixtures-v1'

escape_swift_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

escaped_commit="$(escape_swift_string "$git_commit")"
escaped_branch="$(escape_swift_string "$git_branch")"
escaped_revision="$(escape_swift_string "$contract_revision")"

mkdir -p "$(dirname "$output_path")"
{
  printf '%s\n' '// Generated by generate-build-metadata.sh. Do not edit.'
  printf '%s\n' 'enum GeneratedBuildMetadata {'
  printf '    static let gitCommit = "%s"\n' "$escaped_commit"
  if [[ -n "$git_branch" ]]; then
    printf '    static let gitBranch: String? = "%s"\n' "$escaped_branch"
  else
    printf '%s\n' '    static let gitBranch: String? = nil'
  fi
  printf '    static let isDirty = %s\n' "$is_dirty"
  printf '    static let contractRevision = "%s"\n' "$escaped_revision"
  printf '%s\n' '}'
} > "$output_path"
