/**
 * Extracts SVG path data for the round-outlined-radius-2-stroke-1.5 style
 * from the Mande DS @central-icons-react/all package and writes a TypeScript
 * lookup map to mobile/src/components/ui/icon-paths.ts.
 *
 * Run from repo root: node scripts/extract-icons.js
 */

const fs = require('fs');
const path = require('path');

const ICONS_SOURCE = path.join(
  require('os').homedir(),
  'Mande-DS-and-playground/node_modules/@central-icons-react/all/icons/index.js'
);
const OUTPUT = path.join(__dirname, '../mobile/src/components/ui/icon-paths.ts');
const STYLE = 'round-outlined-radius-2-stroke-1.5';

if (!fs.existsSync(ICONS_SOURCE)) {
  console.error('Icons source not found:', ICONS_SOURCE);
  console.error('Make sure the Mande DS project is at ../../Mande-DS-and-playground');
  process.exit(1);
}

const { centralIcons } = require(ICONS_SOURCE);

const entries = Object.entries(centralIcons)
  .filter(([k]) => k.startsWith(STYLE + '/'))
  .map(([k, v]) => [k.slice(STYLE.length + 1), v]);

const lines = entries.map(([name, content]) => {
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return `  ${name}: \`${escaped}\`,`;
});

const output = `// Generated by scripts/extract-icons.js — do not edit manually.
// Style: ${STYLE} (${entries.length} icons)
// Re-run: node scripts/extract-icons.js

export const iconPaths: Record<string, string> = {
${lines.join('\n')}
};
`;

fs.writeFileSync(OUTPUT, output, 'utf8');
console.log(`Extracted ${entries.length} icons → ${OUTPUT}`);
